name: echopype
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - click
  - dask
  - ipykernel
  - matplotlib
  - numpy
  - netCDF4
  - pandas
  - pip
  - pytz
  - python=3.8
  - requests
  - scipy
  - tox
  - xarray
  - zarr
  - pip:
      - pynmea2