from pathlib import Path
import shutil
import numpy as np
import xarray as xr
import pandas as pd
from scipy.io import loadmat
from ..convert import open_raw

# raw_path = './echopype/data/azfp/17031001.01A'     # Canada (Different ranges)
# xml_path = './echopype/data/azfp/17030815.XML'     # Canada (Different ranges)
azfp_path = Path('./echopype/test_data/azfp')
azfp_01a_path = str(azfp_path.joinpath('17082117.01A'))
azfp_xml_path = str(azfp_path.joinpath('17041823.XML'))
azfp_matlab_data_path = str(azfp_path.joinpath('from_matlab/17082117_matlab_Data.mat'))

csv_paths = ['./echopype/test_data/azfp/from_echoview/17082117-raw38.csv',    # EchoView exports
             './echopype/test_data/azfp/from_echoview/17082117-raw125.csv',
             './echopype/test_data/azfp/from_echoview/17082117-raw200.csv',
             './echopype/test_data/azfp/from_echoview/17082117-raw455.csv']
# raw_paths = ['./echopype/test_data/azfp/set1/' + file
#              for file in os.listdir('./echopype/test_data/azfp/set1')]   # Multiple files (first is xml file)


def test_convert_raw_matlab():

    # Unpacking data
    echodata = open_raw(file=azfp_01a_path, model='AZFP', xml_path=azfp_xml_path)
    echodata.to_netcdf(overwrite=True)

    # Read in the dataset that will be used to confirm working conversions. (Generated by Matlab)
    ds_matlab = loadmat(azfp_matlab_data_path)

    # Test beam group
    with xr.open_dataset(echodata.output_file, group='Beam') as ds_beam:
        # frequency
        assert np.array_equal(ds_matlab['Data']['Freq'][0][0].squeeze(),
                              ds_beam.frequency / 1000)  # matlab file in kHz
        # backscatter count
        assert np.array_equal(np.array([ds_matlab['Output'][0]['N'][fidx] for fidx in range(4)]),
                              ds_beam.backscatter_r.values)
        # tilt x-y
        assert np.array_equal(np.array([d[0] for d in ds_matlab['Data']['Ancillary'][0]]).squeeze(),
                              ds_beam.tilt_x_count)
        assert np.array_equal(np.array([d[1] for d in ds_matlab['Data']['Ancillary'][0]]).squeeze(),
                              ds_beam.tilt_y_count)

    # Test vendor group
    with xr.open_dataset(echodata.output_file, group='Vendor') as ds_vend:
        # Test temperature
        assert np.array_equal(np.array([d[4] for d in ds_matlab['Data']['Ancillary'][0]]).squeeze(),
                              ds_vend.ancillary.isel(ancillary_len=4).values)
        assert np.array_equal(np.array([d[0] for d in ds_matlab['Data']['BatteryTx'][0]]).squeeze(),
                              ds_vend.battery_tx)
        assert np.array_equal(np.array([d[0] for d in ds_matlab['Data']['BatteryMain'][0]]).squeeze(),
                              ds_vend.battery_main)

    Path(echodata.output_file).unlink()

    # TODO: test derived data
    #  - ds_beam.ping_time from 01A raw data records
    #  - investigate why ds_beam.tilt_x/y are different from ds_matlab['Data']['Tx']/['Ty']
    #  - derived temperature


def test_convert_raw_echoview():
    # Compare parsed backscatter data with EchoView generated csv files.

    # Unpacking data
    tmp = Convert(file=azfp_01a_path, model='AZFP', xml_path=azfp_xml_path)
    tmp.to_netcdf()

    # Read in csv files that will be used to confirm working conversions.
    channels = []
    for file in csv_paths:
        channels.append(pd.read_csv(file, header=None, skiprows=[0]).iloc[:, 6:])
    test_power = np.stack(channels)
    with xr.open_dataset(tmp.output_file, group='Beam') as ds_beam:
        assert np.array_equal(test_power, ds_beam.backscatter_r)

    os.remove(tmp.output_file)


def test_convert_zarr():
    # Test saving zarr file. Compare with EchoView generated csv files.
    tmp = Convert(file=azfp_01a_path, model='AZFP', xml_path=azfp_xml_path)
    tmp.to_zarr()
    # Read in csv files that will be used to confirm working conversions.
    channels = []
    for file in csv_paths:
        channels.append(pd.read_csv(file, header=None, skiprows=[0]).iloc[:, 6:])
    test_power = np.stack(channels)
    with xr.open_zarr(tmp.output_file, group='Beam') as ds_beam:
        assert np.array_equal(test_power, ds_beam.backscatter_r)

    shutil.rmtree(tmp.output_file)


# def test_combine():
#     """Test combining multiple raw files"""
#     export_folder = './echopype/test_data/azfp/export/'
#
#     # Test combining while converting
#     tmp = Convert(file=raw_paths[1:5], model='AZFP', xml_path=raw_paths[0])
#     tmp.to_netcdf(save_path=export_folder, overwrite=True, combine=True)
#
#     with xr.open_dataset(tmp.output_file, group='Beam') as ds_beam:
#         # Test if the concatenation along ping time worked
#         assert len(ds_beam.ping_time) == 960
#     shutil.rmtree(export_folder)
