#!/usr/bin/env python

"""
Command line tool for converting sonar data into an interoperable netCDF format.

The tool currently supports converting EK60 .raw to .nc files.
"""

# import argparse
# import os.path
import click
# from echopype.convert.ek60 import ConvertEK60


@click.command()
def main():
    click.echo('Getting into the right module.')


# def main():
#     parser = argparse.ArgumentParser(description='Convert sonar data into an interoperable netCDF (.nc) format.')
#
#     parser.add_argument('-s', '--system', action='store', nargs=1, help="sonar system specifier: 'ek60'")
#     parser.add_argument('-i', '--input-file', action='store', nargs='+', help="pass in one or more .raw files")
#
#     args = parser.parse_args()
#
#     for p in args.input_file:
#         ff = os.path.basename(p)
#         f, ext = os.path.splitext(ff)
#         if not os.path.isfile(f+'.nc'):  # if file has not been converted
#             tmp = ConvertEK60(p)  # create an instance of EK60 converter
#             tmp.raw2nc()   # convert .raw to .nc
#         else:
#             print('This .raw file has been converted before. Delete if you want to convert again.')


if __name__ == '__main__':
    main()
