name: Lint code

on:
  push:
  pull_request:
    branches:
      - master
      - class-redesign

jobs:
  lint-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
      # allow to error for now
      continue-on-error: true