name: Lint code

on:
  push:
    paths-ignore:
      - '.ci_helpers/docker/**'
  pull_request:
    paths-ignore:
      - '.ci_helpers/docker/**'

jobs:
  lint-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
